AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: HelloWorldFunction
      Handler: com.example.HelloWorld::handleRequest
      Role: arn:aws:iam::123456789012:role/execution_role
      Code:
        S3Bucket: my-bucket
        S3Key: my-function.zip
      Runtime: java11
      MemorySize: 512
      Timeout: 30
 
 
