name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # Trigger this workflow on a push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your AWS region

    # Step 3: Validate CloudFormation Template
    - name: Validate CloudFormation Template
      run: |
        aws cloudformation validate-template --template-body file://cloudformation-template.yaml
        

    # Step 4: Deploy CloudFormation Stack
    - name: Deploy CloudFormation Stack
      run: |
        STACK_NAME="lambda-3m"  # Stack name
        TEMPLATE_FILE="cloudformation-template.yaml"  # CloudFormation template
        aws cloudformation deploy --stack-name $STACK_NAME --template-file $TEMPLATE_FILE  --capabilities CAPABILITY_NAMED_IAM --region us-east-1  

    # Step 5: Output the Stack Status
    - name: Check CloudFormation Stack Status
      run: |
        aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].StackStatus"
